### ISSUE TITLE
Patch is incomplete

### ISSUE THREAD

**Issue by spendergrsec** [IAIK/KAISER#1]
The provided patch is incomplete, making it impossible to test.  It's missing at minimum arch/x86/include/asm/kaiser.h which I assume provides the SWITCH_\*_CR3\* macros.

Seems to have been an oversight during this change:
https://github.com/IAIK/KAISER/commit/7e6388753615b8ecef5f68835db2f42235e2938a

-Brad

**Comment by dgruss** [comment]
yes, thanks for finding this. we will update the file asap.

**Comment by spendergrsec** [comment]
arch/x86/mm/kaiser.c is also missing

**Comment by mlq** [comment]
My mistake. I've updated the patch file already.

**Comment by spendergrsec** [comment]
Works now, thank you!

-Brad
